-- Archivo para introducir las preguntas de Terman en el catálogo preguntasTerman

INSERT INTO preguntasTerman(idPreguntaTerman,idSerieTerman, numeroPregunta, preguntaTerman)
VALUES

-- Serie 1:

(1, 1, 1, 'La gasolina se extrae de: '),
(2, 1, 2, 'Una tonelada tiene: '),
(3, 1, 3, 'La mayoría de nuestras exportaciones salen por: '),
(4, 1, 4, 'El nervio óptico sirve para: '),
(5, 1, 5, 'El café es una especie de: '),
(6, 1, 6, 'El jamón es carne de: '),
(7, 1, 7, 'La laringe está en: '),
(8, 1, 8, 'La guillotina causa la: '),
(9, 1, 9, 'La grúa se usa para: '),
(10, 1, 10, 'Un figura de seis lados se llama: '),
(11, 1, 11, 'El kilowatt mide:' ),
(12, 1, 12, 'La pauta se usa en: '),
(13, 1, 13, 'Las esmeraldas son: '),
(14, 1, 14, 'El metro es aproximadamente igual a: '),
(15, 1, 15, 'Las esponjas se obtienen de: '),
(16, 1, 16, 'Fraude es un término usado en: '),

-- Serie 2:

(17, 2, 1, 'Si la tierra estuviera más cerca del sol: '),
(18, 2, 2, 'Los rayos de una rueda están frecuentemente hechos de nogal porque: '),
(19, 2, 3, 'Un tren se detiene con más dificultad que un automóvil porque: '),
(20, 2, 4, 'El dicho "A golpecitos se derriba un roble", quiere decir: '),
(21, 2, 5, 'El dicho "Una olla vigilada nunca hierve", quiere decir: '),
(22, 2, 6, 'El dicho "Siembra pasto mientras haya sol", quiere decir: '),
(23, 2, 7, 'El dicho "Zapatero a tus zapatos", quiere decir: '),
(24, 2, 8, 'El dicho: "La cuña para que apriete debe de ser del mismo palo" quiere decir: '),
(25, 2, 9, 'Un acorazado de acero flota porque: '),
(26, 2, 10, 'Las plumas de las alas ayudan al pájaro a volar porque: '),
(27, 2, 11, 'El dicho: "Una golondrina no hace verano", quiere decir: '),

-- Serie 3:

(28, 3, 1,'Salado - Dulce'),
(29, 3, 2,'Alegrarse - Regocijarse'),
(30, 3, 3,'Mayor - Menor'),
(31, 3, 4,'Sentarse - Pararse'),
(32, 3, 5,'Desperdiciar - Aprovechar'),
(33, 3, 6,'Conceder - Negar'),
(34, 3, 7,'Tónico - Estimulante'),
(35, 3, 8,'Rebajar - Denigrar'),
(36, 3, 9,'Prohibir - Permitir'),
(37, 3, 10,'Osadía - Audaz'),
(38, 3, 11,'Arrebatado - Prudente'),
(39, 3, 12,'Obtuso - Agudo'),
(40, 3, 13,'Inepto - Experto'),
(41, 3, 14,'Esquivar - Rehuir'),
(42, 3, 15,'Rebelarse - Someterse'),
(43, 3, 16,'Monotonía - Variedad'),
(44, 3, 17,'Confrontar - Consolar'),
(45, 3, 18,'Expeler - Retener'),
(46, 3, 19,'Dócil - Sumiso'),
(47, 3, 20,'Transitorio - Permanente'),
(48, 3, 21,'Seguridad - Riesgo'),
(49, 3, 22,'Aprobar - Objetar'),
(50, 3, 23,'Expeler - Arrojar'),
(51, 3, 24,'Engaño - Impostura'),
(52, 3, 25,'Mitigar - Apaciguar'),
(53, 3, 26,'Incitar - Aplacar'),
(54, 3, 27,'Reverencia - Veneración'),
(55, 3, 28,'Sobriedad - Frugalidad'),
(56, 3, 29,'Aumentar - Menguar'),
(57, 3, 30,'Incitar - Instigar'),

-- Serie 4:

(58, 4, 1,'UN CIRCULO tiene siempre:'),
(59, 4, 2,'UN PAJARO tiene siempre:'),
(60, 4, 3,'LA MUSICA tiene siempre:'),
(61, 4, 4,'UN BANQUETE tiene siempre:'),
(62, 4, 5,'UN CABALLO tiene siempre:'),
(63, 4, 6,'UN JUEGO tiene siempre:'),
(64, 4, 7,'UN OBJETO tiene siempre:'),
(65, 4, 8,'UNA CONVERSACION tiene siempre:'),
(66, 4, 9,'UNA DEUDA tiene siempre:'),
(67, 4, 10,'UN CIUDADANO tiene siempre:'),
(68, 4, 11,'UN MUSEO tiene siempre:'),
(69, 4, 12,'UN COMPROMISO implica siempre:'),
(70, 4, 13,'UN BOSQUE tiene siempre:'),
(71, 4, 14,'LOS OBSTACULOS tienen siempre:'),
(72, 4, 15,'EL ABORRECIMIENTO tiene siempre:'),
(73, 4, 16,'UNA REVISTA tiene siempre:'),
(74, 4, 17,'LA CONTROVERSIA implica siempre:'),
(75, 4, 18,'UN BARCO tiene siempre:'),

-- Serie 5:

(76, 5, 1,'A 2 por 5 centavos, ¿Cuántos lápices pueden comprarse con 50 centavos?'),
(77, 5, 2,'¿Cuántas horas tardará un automóvil en recorrer 660 kilómetros a la velocidad de 60 kilómetros por hora?'),
(78, 5, 3,'Si un hombre gana $20.00 diarios y gasta $14.00 ¿cuántos días tardará en ahorrar $ 300.00?'),
(79, 5, 4,'Si dos pasteles cuestan $ 0.60, ¿cuántos centavos cuesta la sexta parte de un pastel?'),
(80, 5, 5,'¿Cuántas veces más es 2 X 3 X 4 X 5, que 3 X 4?'),
(81, 5, 6,'¿Cuánto es el 16 por ciento de 120?'),
(82, 5, 7,'El cuatro por ciento de $ 1,000 es igual al ocho por ciento de ¿qué cantidad?'),
(83, 5, 8,'La capacidad de un refrigerador rectangular es de 48 metros cúbicos. Si tiene seis metros de largo por cuatro de ancho, ¿cuál es su altura?'),
(84, 5, 9,'Si 7 hombres hacen un pozo de 40 metros en dos días, ¿cuántos hombres se necesitan para hacerlo en medio día?'),
(85, 5, 10,'A, tiene $180.00; B, tiene 2/3 de lo que tiene A; C 1/2 de lo que tiene B, ¿cuánto tienen todos juntos?'),
(86, 5, 11,'Si un hombre corre 100 metros en 10 segundos, ¿cuántos metros recorrerá como promedio en 1/5 de segundo?'),
(87, 5, 12,'Un hombre gasta ¼ de su sueldo en casa y alimentos y 4/8 en otros gastos, ¿qué tanto por ciento de su sueldo ahorra?'),

-- Serie 6:

(88, 6, 1,'La higiene, ¿es esencial para la salud?'),
(89, 6, 2,'Los taquígrafos, ¿usan el microscopio?'),
(90, 6, 3,'Los tiranos, ¿son justos con sus inferiores?'),
(91, 6, 4,'Las personas desamparadas, ¿están sujetas con frecuencia a la caridad?'),
(92, 6, 5,'Las personas venerables, ¿son por lo común respetadas?'),
(93, 6, 6,'Es el escorbuto, ¿un medicamento?'),
(94, 6, 7,'Es la amonestación, ¿una clase de instrumento musical?'),
(95, 6, 8,'Son los colores opacos, ¿preferidos por las banderas nacionales?'),
(96, 6, 9,'Las cosas misteriosas, ¿son, a veces, pavorosas?'),
(97, 6, 10,'Las personas conscientes, ¿cometen alguna vez errores?'),
(98, 6, 11,'¿Son carnívoros los carneros?'),
(99, 6, 12,'¿Se dan asignaturas a los caballos?'),
(100, 6, 13,'Las cartas anónimas, ¿llevan alguna vez firma de quien las escribe?'),
(101, 6, 14,'¿Son discontinuos los sonidos intermitentes?'),
(102, 6, 15,'Las enfermedades, ¿estimulan el buen juicio?'),
(103, 6, 16,'¿Son siempre perversos los hechos premeditados?'),
(104, 6, 17,'El contacto social, ¿tiende a reducir la timidez?'),
(105, 6, 18,'¿Son enfermas las personas que tienen mal carácter?'),
(106, 6, 19,'Se caracteriza generalmente el rencor, ¿por la persistencia?'),
(107, 6, 20,'Meticuloso ¿quiere decir lo mismo que cuidadoso?'),

-- Serie 7:

(108, 7, 1,'ABRIGO es a USAR como el PAN es a:'),
(109, 7, 2,'SEMANA es a MES como MES es a:'),
(110, 7, 3,'LEON es a ANIMAL como ROSA es a:'),
(111, 7, 4,'LIBERTAD es a INDEPENDENCIA como CAUTIVERIO es a:'),
(112, 7, 5,'DECIR es a DIJO como ESTAR es a: '),
(113, 7, 6,'LUNES es a MARTES como VIERNES es a:'),
(114, 7, 7,'PLOMO es a PESADO como CORCHO es a:'),
(115, 7, 8,'EXITO es a ALEGRIA como FRACASO es a:'),
(116, 7, 9,'GATO es a TIGRE como PERRO es a:'),
(117, 7, 10,'4 es a 16 como 5 es a:'),
(118, 7, 11,'LLORAR es a REIR como TRISTE es a:'),
(119, 7, 12,'VENENO es a MUERTE como ALIMENTO es a:'),
(120, 7, 13,'1 es a 3 como 9 es a:'),
(121, 7, 14,'ALIMENTO es a HAMBRE como AGUA es a:'),
(122, 7, 15,'AQUI es a ALLI como ESTE es a:'),
(123, 7, 16,'TIGRE es a PELO como TRUCHA es a:'),
(124, 7, 17,'PERVERTIDO es a DEPRAVADO como INCORRUPTO es a:'),
(125, 7, 18,'B es a D como SEGUNDO es a:'),
(126, 7, 19,'ESTADO es a GOBERNADOR como EJERCITO es a:'),
(127, 7, 20,'SUJETO es a PREDICADO como NOMBRE es a:'),

-- Serie 8:

(128, 8, 1,'con crecen los niños edad la'),
(129, 8, 2,'buena mar beber el para agua de es'),
(130, 8, 3,'lo es paz la guerra opuesta la a'),
(131, 8, 4,'caballos automóvil un que caminan los despacio más'),
(132, 8, 5,'consejo a veces es buen seguir un difícil'),
(133, 8, 6,'cuatrocientos todas páginas contienen libros los'),
(134, 8, 7,'crecen las que fresas el roble más'),
(135, 8, 8,'verdadera la comparada no puede amistad ser'),
(136, 8, 9,'envidia la perjudicial gula son y la'),
(137, 8, 10,'nunca acciones premiadas las deben buenas ser'),
(138, 8, 11,'exteriores engañan nunca apariencias las nos'),
(139, 8, 12,'nunca es hombre las que acciones demuestran un lo'),
(140, 8, 13,'ciertas siempre muerte de causan clases enfermedades'),
(141, 8, 14,'odio indeseables aversión sentimientos el son y la'),
(142, 8, 15,'frecuentemente por juzgar podemos acciones hombres nosotros sus a los'),
(143, 8, 16,'una es sábana sarapes tan nunca los caliente como'),
(144, 8, 17,'nunca que descuidados los tropiezan son'),

-- Serie 9:

(145, 9, 1,'Ponga la letra de la palabra que no corresponda con las demás del renglón'),
(146, 9, 2,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(147, 9, 3,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(148, 9, 4,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(149, 9, 5,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(150, 9, 6,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(151, 9, 7,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(152, 9, 8,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(153, 9, 9,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(154, 9, 10,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(155, 9, 11,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(156, 9, 12,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(157, 9, 13,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(158, 9, 14,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(159, 9, 15,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(160, 9, 16,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(161, 9, 17,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),
(162, 9, 18,'Ponga la letra de la palabra que no corresponda con las demás del renglóna'),

-- Serie 10:

(163, 10, 1,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(164, 10, 2,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(165, 10, 3,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(166, 10, 4,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(167, 10, 5,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(168, 10, 6,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(169, 10, 7,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(170, 10, 8,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(171, 10, 9,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(172, 10, 10,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie'),
(173, 10, 11,'En cada renglón procure encontrar como están hechas las series, después, escriba en la hoja de respuestas, los DOS números que deban seguir en cada serie');
